### ISSUE TITLE
bazelvis main:hello-world got nothing

### ISSUE THREAD

**Issue by PikachuHyA** [jamesma100/bazelvis#1]
Hi,

I discovered this intriguing tool on Reddit and decided to give it a try. 

When I tested with a Bazel project using the command `bazelvis src:bazel` on my macOS, it didn't return any results. However, using the command `//src:bazel` worked fine.

Similarly, when I tested with `main:hello-world`, it also didn't return any results, while `//main:hello-world` worked as expected.

Could you please look into this issue? Thanks in advance for your help!

**Comment by jamesma100** [comment]
hi @PikachuHyA this has been fixed. thanks for reporting

**Comment by PikachuHyA** [comment]
great. thanks
